In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandasgui
from warnings import filterwarnings
filterwarnings("ignore")

## Import dataset

In [2]:
data=pd.read_csv("Dataset_national_trains.csv", sep=";")

display(data.head(10))

,year,month,date,service,depart_st,arrival_st,avg_duration,exp_monthly_trains,cancelled_nb,delay>15,delay>30,delay>60,delay_external,delay_infrastructure,delay_traffic_management,delay_rolling_stock,delay_station_management,delay_passenger_related
0,2018,Jan,2018-01-01,National,BORDEAUX ST JEAN,PARIS MONTPARNASSE,141,870,5,110,44,8,36.13,31.09,10.92,15.97,5.04,0.84
1,2018,Jan,2018-01-01,National,LA ROCHELLE VILLE,PARIS MONTPARNASSE,165,222,0,22,5,0,15.38,30.77,38.46,11.54,3.85,0.00
2,2018,Jan,2018-01-01,National,PARIS MONTPARNASSE,QUIMPER,220,248,1,26,17,7,26.92,38.46,15.38,19.23,0.00,0.00
3,2018,Jan,2018-01-01,National,PARIS MONTPARNASSE,ST MALO,156,102,0,8,6,4,23.08,46.15,7.69,15.38,7.69,0.00
4,2018,Jan,2018-01-01,National,PARIS MONTPARNASSE,ST PIERRE DES CORPS,61,391,2,17,6,0,21.21,42.42,9.09,21.21,6.06,0.00
5,2018,Jan,2018-01-01,National,QUIMPER,PARIS MONTPARNASSE,223,256,1,21,9,2,27.78,55.56,0.00,5.56,5.56,5.56
6,2018,Jan,2018-01-01,National,RENNES,LYON PART DIEU,233,99,0,6,2,1,0.00,50.00,25.00,25.00,0.00,0.00
7,2018,Jan,2018-01-01,National,ST PIERRE DES CORPS,PARIS MONTPARNASSE,61,410,1,26,9,0,22.73,45.45,16.67,12.12,1.52,1.52
8,2018,Jan,2018-01-01,National,TOURS,PARIS MONTPARNASSE,75,194,0,7,1,0,25.00,56.25,6.25,12.50,0.00,0.00
9,2018,Jan,2018-01-01,National,NANTES,STRASBOURG,303,39,0,5,2,1,0.00,0.00,33.33,33.33,0.00,33.33

##  Sorting

In [4]:
national_data = data[(data['year'] == 2023) & (data['service'] == 'National')]  # filter for year 2023

display(national_data.tail(5))    #use display instead of print to get a nice table view!"""

,year,month,date,service,depart_st,arrival_st,avg_duration,exp_monthly_trains,cancelled_nb,delay>15,delay>30,delay>60,delay_external,delay_infrastructure,delay_traffic_management,delay_rolling_stock,delay_station_management,delay_passenger_related
8869,2023,Dec,2023-12-01,National,PARIS MONTPARNASSE,BREST,230,276,2,29,9,3,37.93,3.45,10.34,20.69,17.24,10.34
8870,2023,Dec,2023-12-01,National,PARIS MONTPARNASSE,TOULOUSE MATABIAU,264,219,4,43,28,10,46.51,9.30,13.95,11.63,4.65,13.95
8871,2023,Dec,2023-12-01,National,PARIS NORD,DOUAI,71,136,0,11,2,1,10.53,5.26,15.79,47.37,15.79,5.26
8872,2023,Dec,2023-12-01,National,STRASBOURG,NANTES,337,61,0,9,6,1,25.00,12.50,0.00,37.50,25.00,0.00
8873,2023,Dec,2023-12-01,National,TOURS,PARIS MONTPARNASSE,74,188,3,4,2,1,13.33,26.67,40.00,13.33,0.00,6.67